image: docker:latest

services:
  - docker:dind

variables:
  IMAGE_NAME: registry.gitlab.com/<achmadfaizal726>/<hello-docker>

stages:
  - build
  - push

before_script:
  # LOGIN otomatis ke GitLab Container Registry
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

build_image:
  stage: build
  script:
    - docker build -t $hello-docker:v1 .

push_image:
  stage: push
  script:
    - docker push $hello-docker:v1
